spring.application.name=Backend
server.port=8081
spring.mongodb.uri=mongodb+srv://fukeraju03_db_user:idqNbNhtGdkyRy3I@cluster0.sjoi1fe.mongodb.net/sample_mflix?appName=Cluster0

# Real-time AQI configuration
# Register for a token at https://aqicn.org/data-platform/token/
aqi.waqi.token=884f3005a68a740b6515f47b76b00afe0720415c
aqi.waqi.base-url=https://api.waqi.info
# https://api.weatherapi.com/v1/current.json?key=a8e2afdb63024bd3a81143342260708&q=Mumbai&aqi=yes
